name: build

on:
  workflow_call:
    inputs:
      helmEventTargetRepository:
        description: 'Target repository'
        default: ''
        required: false
        type: string
        
jobs:
  codeql:
    uses: onecx/ci-angular/.github/workflows/angular-codeql.yml@v1
    secrets: inherit
  angular:
    uses: onecx/ci-angular/.github/workflows/angular-build.yml@v1
    secrets: inherit
  docker:
    uses: onecx/ci-common/.github/workflows/docker-build.yml@v1
    needs: angular
    secrets: inherit
    with:
      tags: '{{ .Version }},{{ .Branch }}'
      push: true
      samoDockerFile: Dockerfile
  sonar:
    uses: onecx/ci-angular/.github/workflows/angular-sonar.yml@v1
    needs: docker
    secrets: inherit
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    needs: docker
    secrets: inherit
    with:
      push: true
      helmDir: 'helm'
  helm-event:
    if: ${{ inputs.helmEventTargetRepository != '' }}
    uses: onecx/ci-product/.github/workflows/helm-send-event.yml@v1
    needs: helm
    secrets: inherit
    with:
      targetRepository: ${{ inputs.helmEventTargetRepository }}
      